# https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
# https://github.com/synacktiv/octoscan/blob/master/core/rules/rule_runner_label.go
# https://github.com/actions/runner-images
supported_runners:
  - ubuntu-latest
  - ubuntu-24.04
  - ubuntu-22.04
  - ubuntu-20.04
  - ubuntu-latest-4-cores
  - ubuntu-latest-8-cores
  - ubuntu-latest-16-cores
  - ubuntu-24.04-arm
  - ubuntu-22.04-arm
  - windows-latest
  - windows-latest-8-cores
  - windows-2025
  - windows-2022
  - windows-11-arm
  - macos-14
  - macos-15
  - macos-latest
  - macos-latest-large
  - macos-latest-xlarge
  - macos-latest-xl
  - macos-14-large
  - macos-15-large
  - macos-14-xlarge
  - macos-15-xlarge

unsupported_runners:
  - ubuntu-18.04
  - ubuntu-16.04
  - macos-13
  - macos-13-large
  - macos-13-xlarge
  - macos-12
  - macos-12-large
  - macos-12-xlarge
  - macos-11
  - macos-10.15
  - windows-2019
  - windows-2016

trusted-orgs:
  - actions
  - advanced-security
  - github
  - docker

deprecated-actions:
  - actions/cache@v1
  - actions/cache@v2
  - actions/upload-artifact@v1
  - actions/upload-artifact@v2
  - actions/upload-artifact@v3
  - actions/download-artifact@v1
  - actions/download-artifact@v2
  - actions/download-artifact@v3
